version: '3.8'

services:

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    env_file: 
      - .env
    ports:
      - 5432:5432

  django:
    image: cimmke/funds:dev
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    command: python manage.py runserver 0:8000

volumes:
  db_data: {}