# Generated by Django 3.1.5 on 2021-01-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_auto_20210112_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postings',
            name='posting_type',
        ),
        migrations.AddField(
            model_name='postings',
            name='posting_types',
            field=models.CharField(choices=[('standard', 'Standard'), ('income', 'Income'), ('transfer', 'Transfer')], default='standard', max_length=30),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('cash', 'Cash'), ('credit_card', 'Credit Card'), ('line_of_credit', 'Line of Credit'), ('investment', 'Investment'), ('other_liability', 'Other Liability or Loan'), ('other_asset', 'Other Asset')], default='cash', max_length=30),
        ),
        migrations.DeleteModel(
            name='AccountTypes',
        ),
        migrations.DeleteModel(
            name='PostingTypes',
        ),
    ]
