# Generated by Django 3.1.5 on 2021-01-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_auto_20210112_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postings',
            old_name='posting_types',
            new_name='posting_type',
        ),
    ]
